game.keys = [];
for (var i = 0; i < 255; ++i) game.keys[i] = false;

document.onkeydown = function(e) {
  game.keys[e.which] = true;
  return false;
}
document.onkeyup = function(e) {
  game.keys[e.which] = false;
  return false;
}

var key = {
  cancel: function() { return game.keys[3]; },
  backspace: function() { return game.keys[8]; },
  tab: function() { return game.keys[9]; },
  enter: function() { return game.keys[14]; },
  shift: function() { return game.keys[16]; },
  control: function() { return game.keys[17]; },
  alt: function() { return game.keys[18]; },
  pause: function() { return game.keys[19]; },
  capsLock: function() { return game.keys[20]; },
  escape: function() { return game.keys[27]; },
  space: function() { return game.keys[32]; },
  pageUp: function() { return game.keys[33]; },
  pageDown: function() { return game.keys[34]; },
  end: function() { return game.keys[35]; },
  home: function() { return game.keys[36]; },
  left: function() { return game.keys[37]; },
  up: function() { return game.keys[38]; },
  right: function() { return game.keys[39]; },
  down: function() { return game.keys[40]; },
  printscreen: function() { return game.keys[44]; },
  insert: function() { return game.keys[45]; },
  del: function() { return game.keys[46]; },
  number0: function() { return game.keys[48]; },
  number1: function() { return game.keys[49]; },
  number2: function() { return game.keys[50]; },
  number3: function() { return game.keys[51]; },
  number4: function() { return game.keys[52]; },
  number5: function() { return game.keys[53]; },
  number6: function() { return game.keys[54]; },
  number7: function() { return game.keys[55]; },
  number8: function() { return game.keys[56]; },
  number9: function() { return game.keys[57]; },
  semicolon: function() { return game.keys[59]; },
  equals: function() { return game.keys[61]; },
  a: function() { return game.keys[65]; },
  b: function() { return game.keys[66]; },
  c: function() { return game.keys[67]; },
  d: function() { return game.keys[68]; },
  e: function() { return game.keys[69]; },
  f: function() { return game.keys[70]; },
  g: function() { return game.keys[71]; },
  h: function() { return game.keys[72]; },
  i: function() { return game.keys[73]; },
  j: function() { return game.keys[74]; },
  k: function() { return game.keys[75]; },
  l: function() { return game.keys[76]; },
  m: function() { return game.keys[77]; },
  n: function() { return game.keys[78]; },
  o: function() { return game.keys[79]; },
  p: function() { return game.keys[80]; },
  q: function() { return game.keys[81]; },
  r: function() { return game.keys[82]; },
  s: function() { return game.keys[83]; },
  t: function() { return game.keys[84]; },
  u: function() { return game.keys[85]; },
  v: function() { return game.keys[86]; },
  w: function() { return game.keys[87]; },
  x: function() { return game.keys[88]; },
  y: function() { return game.keys[89]; },
  z: function() { return game.keys[90]; },
  contextMenu: function() { return game.keys[93]; },
  numpad0: function() { return game.keys[96]; },
  numpad1: function() { return game.keys[97]; },
  numpad2: function() { return game.keys[98]; },
  numpad3: function() { return game.keys[99]; },
  numpad4: function() { return game.keys[100]; },
  numpad5: function() { return game.keys[101]; },
  numpad6: function() { return game.keys[102]; },
  numpad7: function() { return game.keys[103]; },
  numpad8: function() { return game.keys[104]; },
  numpad9: function() { return game.keys[105]; },
  multiply: function() { return game.keys[106]; },
  add: function() { return game.keys[107]; },
  separator: function() { return game.keys[108]; },
  subtract: function() { return game.keys[109]; },
  decimal: function() { return game.keys[110]; },
  divide: function() { return game.keys[111]; },
  f1: function() { return game.keys[112]; },
  f2: function() { return game.keys[113]; },
  f3: function() { return game.keys[114]; },
  f4: function() { return game.keys[115]; },
  f5: function() { return game.keys[116]; },
  f6: function() { return game.keys[117]; },
  f7: function() { return game.keys[118]; },
  f8: function() { return game.keys[119]; },
  f9: function() { return game.keys[120]; },
  f10: function() { return game.keys[121]; },
  f11: function() { return game.keys[122]; },
  f12: function() { return game.keys[123]; },
  f13: function() { return game.keys[124]; },
  f14: function() { return game.keys[125]; },
  f15: function() { return game.keys[126]; },
  f16: function() { return game.keys[127]; },
  f17: function() { return game.keys[128]; },
  f18: function() { return game.keys[129]; },
  f19: function() { return game.keys[130]; },
  f20: function() { return game.keys[131]; },
  f21: function() { return game.keys[132]; },
  f22: function() { return game.keys[133]; },
  f23: function() { return game.keys[134]; },
  f24: function() { return game.keys[135]; },
  num_lock: function() { return game.keys[144]; },
  scroll_lock: function() { return game.keys[145]; },
  comma: function() { return game.keys[188]; },
  period: function() { return game.keys[190]; },
  slash: function() { return game.keys[191]; },
  back_quote: function() { return game.keys[192]; },
  open_bracket: function() { return game.keys[219]; },
  back_slash: function() { return game.keys[220]; },
  close_bracket: function() { return game.keys[221]; },
  quote: function() { return game.keys[222]; },
  meta: function() { return game.keys[224]; }
};